# Generated by Django 2.1.5 on 2024-10-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronogramas', '0002_alter_cronograma_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plantillacronograma',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
