# Generated by Django 5.1.1 on 2024-10-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('nit', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('grado', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('jornada', models.CharField(max_length=50)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('acudientes', models.ManyToManyField(related_name='estudiantes', to='instituciones.acudiente')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.colegio')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.grado')),
            ],
        ),
    ]
