# Generated by Django 5.1.1 on 2024-10-01 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.acudiente')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.factura')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden'),
        ),
    ]
