# Generated by Django 3.2.6 on 2024-10-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_orden_plantilla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordenes.metodopago'),
        ),
    ]
