# Generated by Django 5.1.1 on 2024-10-01 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituciones.colegio')),
                ('estudiantes', models.ManyToManyField(related_name='cronogramas', to='instituciones.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaCronograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_desde', models.DateTimeField()),
                ('fecha_hasta', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='cronogramas.cronograma')),
            ],
        ),
    ]
