# Generated by Django 3.2.6 on 2024-10-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
        ('cronogramas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='cronogramas', to='instituciones.Estudiante'),
        ),
    ]
