# Generated by Django 3.2.6 on 2024-12-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_auto_20241201_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='plantilla',
        ),
    ]
